### ISSUE TITLE
How to use prototype to classify close-set?

### ISSUE THREAD

**Issue by promefire** [Yifei-Y/Openset-RCNN#1]
Thanks for your intersting job. In the paper,i find "We find that the close-set classification performance of the latent space is not as well as the traditional softmax classifier. So after identifying known and unknown objects using the latent space constructed by PLN, we apply a softmax classifier on all known objects to classify them into each known category." I want to use the former for closed set classification, what modifications should I make?

**Comment by Yifei-Y** [comment]
You can compute the distances between the proposal feature and prototypes of all known classes. Then classify the proposal into the class with the minimum distance.

**Comment by jannehlamin** [comment]
I think base on your question, you should change the eval_type to "Closeset" instead of "openset" .
