### ISSUE TITLE
使用模型

### ISSUE THREAD

**Issue by fengjie215** [Yifei-Y/Openset-RCNN#2]
感谢您的工作，我想将在graspnet数据集上训练的模型也运用到我的机器人抓取项目中，想请问一下如何使用您已训练的模型，对单张场景图片生成物体的bounding box？

**Comment by jannehlamin** [comment]
I think this is what you need, and try to make Facebook detectron2 github repository your friend for this project .

https://github.com/facebookresearch/detectron2/blob/main/tools/visualize_json_results.py

**Comment by Yifei-Y** [comment]
> 感谢您的工作，我想将在graspnet数据集上训练的模型也运用到我的机器人抓取项目中，想请问一下如何使用您已训练的模型，对单张场景图片生成物体的bounding box？

测试时的推理是用dataloader把测试数据集加载进来然后对每张图片进行前向传播得到推理结果，所以您可以参考推理部分的代码进行修改
