### ISSUE TITLE
Opensen prediction is always negative hundred (-100), which is show in the screenshot, what must have been the issue?

### ISSUE THREAD

**Issue by jannehlamin** [Yifei-Y/Openset-RCNN#3]
I have used different datasets and yet these output of the open set version still remain like this in the screenshot

![A11](https://github.com/Yifei-Y/Openset-RCNN/assets/8759860/328c228d-679e-4542-b530-3104c42b731c)

**Comment by Yifei-Y** [comment]
Could you tell me what changes you made to the code? The code contains some parameters related to the dataset. The reason for the strange results should be that these parameters are not modified accordingly.

**Comment by jannehlamin** [comment]
Thank for the reply and the job well-done on this project. I have used custom dataset and the only parameter modified here is as follows:

`DATASETS:
  TRAIN: ('cropweed_train', 'cropweed_val')
  TEST: ('cropweed_test',)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.005
  STEPS: (400, 500)
  MAX_ITER: 4000
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 100
TEST:
  DETECTIONS_PER_IMAGE: 100
INPUT:
  MIN_SIZE_TRAIN: (512,)`

otherwise anything remains the same.

**Comment by Yifei-Y** [comment]
There are at least the following changes that need to be made:

- set the `NUM_CLASSES` and `NUM_KNOWN_CLASSES` in the config file.
- set `KNOWN_CATEGORIES` and `KNOWN_IDS` in your dataset_meta.py like openset_rcnn/data/graspnet_meta.py (line 92-100)
- import and use `KNOWN_IDS` in openset_rcnn/modeling/roi_heads/prototype_learning_network.py and openset_rcnn/modeling/roi_heads/softmax_classifier.py
- import and use `KNOWN_CATEGORIES` and `KNOWN_IDS` in openset_rcnn/evaluation/os_coco_evaluation.py

**Comment by jannehlamin** [comment]
Actually, I change everything as you suggested and it is detecting the known class unfortunately the unknown class is still NAN as shown in the screenshot above. May, I should change the loss function?

**Comment by Yifei-Y** [comment]
Have you checked the number of gt unknown objects during evaluation? Could you show me the full evaluation output including both known and unknown metric?

**Comment by jannehlamin** [comment]
I have not given up,and thanks for your support once again. 

Ever-since, I saw your request for the unknown groundtruth, I decided to add the groundtruth for the unknown as well. Then,I decided to re-train the program and the reverse occur,and there is the results of the unkowns with correct prediction and the knowns with series of -1s. The screenshot below shows the results of both know and unkowns.
A. unknows
![unknows](https://github.com/Yifei-Y/Openset-RCNN/assets/8759860/98366c0a-4f79-48b2-80bf-394f594f4007)
B. knowns
![b](https://github.com/Yifei-Y/Openset-RCNN/assets/8759860/6ab21386-d341-4a42-acbf-525cedf351e5)

Troubleshooting 1: while I was also trying to find the solution

1.  I detect that in you in your unofficial implementation of the cocoevaluation , this precisions below is always empty:

`precisions = coco_eval.eval_kdt["precision"]\n
            print("Jannehlamin--------",precisions)`

2.  The output of the coco_eval.eval_kdt is:
`{'params': <pycocotools.cocoeval.Params object at 0x7f1067d6f040>, 'counts': [10, 101, 0, 4, 5], 'date': '2024-06-11 06:13:34', 'precision': array([], shape=(10, 101, 0, 4, 5), dtype=float64), 'recall': array([], shape=(10, 0, 4, 5), dtype=float64), 'scores': array([], shape=(10, 101, 0, 4, 5), dtype=float64), 'ok_det_as_known': array([], shape=(10, 0, 4, 5), dtype=float64), 'unk_det_as_known': array([], shape=(10, 0, 4, 5), dtype=float64), 'tp_plus_fp_cs': array([], shape=(10, 101, 0, 4, 5), dtype=float64), 'fp_os': array([], shape=(10, 101, 0, 4, 5), dtype=float64)}
`


3. AssertionError: assert len(class_names) == precisions.shape[2]

**Comment by jannehlamin** [comment]
After strenuous effort, I was able to resolve the problem. so for the benefit of others. I was using custom dataset which has a subtle annotation difference with the standard coco annotation. Obviously, these variations will have an impact in the coco evaluation functions. 
`cat_ids = sorted(coco_gt.getCatIds(catNms=known_names))` , 

As for my case , accessing the the cat_ids by categories name  failed because the category "name" in my json file is "name":"None", as indicated in the screenshot below:
[
![AA](https://github.com/facebookresearch/detectron2/assets/8759860/ee8ee6a1-85d9-4dfb-8bc2-d2a9b073fbc2)
](url)

Solution: I provided keys for cat_Ids instead of  using the cat_Ids queries function from the coco api
` cat_ids = sorted(known_ids)
    # cat_ids = sorted(coco_gt.getCatIds(catNms=known_names))
    coco_eval.params.catIds = cat_ids`

Finally, everything works as expected. Thank you for the job well-done!

**Comment by Yifei-Y** [comment]
Congratulations on getting it fixed! Yeah, I write the code for the standard coco format. Thank you for your update and for letting me know that the issue has been resolved.
